version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: maf
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432

  app:
    image: maf-bot-image
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080

  redis:
    image: redis:alpine
    ports:
      - 6379:6379